# Generated by Django 5.2 on 2025-05-01 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('revised', 'ปรับแก้ไข'), ('approved', 'ลูกค้าอนุมัติ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็นใบแจ้งหนี้')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_api.cashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_api.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_api.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_api.quotation')),
            ],
            options={
                'unique_together': {('quotation', 'product')},
            },
        ),
    ]
