# Generated by Django 5.2 on 2025-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_quotation_status_cashsaleitem_invoiceitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('pending', 'รออนุมัติ'), ('revised', 'ปรับแก้ไข'), ('approved', 'ลูกค้าอนุมัติ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็นใบแจ้งหนี้')], max_length=50, null=True),
        ),
    ]
