# Generated by Django 5.2 on 2025-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0003_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('pending', 'รออนุมัติ'), ('revised', 'ปรับแก้ไข'), ('approved', 'ลูกค้าอนุมัติ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็นใบแจ้งหนี้')], default='pending', max_length=20),
        ),
    ]
