# Generated by Django 5.2 on 2025-05-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0004_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotationitem',
            unique_together=set(),
        ),
    ]
