# Generated by Django 5.2 on 2025-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0005_alter_quotationitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
