# Generated by Django 5.2 on 2025-05-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0006_alter_quotation_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='invoice',
        ),
        migrations.AddField(
            model_name='receipt',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='pos_api.quotation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'แบบร่าง'), ('sent', 'ส่งแล้ว'), ('pending', 'รออนุมัติ'), ('revised', 'ปรับแก้ไข'), ('approved', 'ลูกค้าอนุมัติ'), ('rejected', 'ลูกค้าปฏิเสธ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็นใบเสร็จรับเงิน')], default='pending', max_length=20),
        ),
    ]
