# Generated by Django 5.2 on 2025-05-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0007_alter_quotation_options_remove_receipt_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pos_api.invoice'),
        ),
    ]
