# Generated by Django 5.2 on 2025-05-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0008_receipt_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('sent', 'ส่งแล้ว'), ('pending', 'รออนุมัติ'), ('approved', 'ดำเนินการแล้ว'), ('Not approved', 'ไม่ได้รับการอนุมัติ'), ('converted', 'แปลงเป็นใบเสร็จรับเงิน')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pos_api.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
