# Generated by Django 5.2 on 2025-05-05 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0010_receiptitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptitem',
            old_name='unit_price',
            new_name='price_per_unit',
        ),
        migrations.AlterUniqueTogether(
            name='receiptitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
