# Generated by Django 5.2 on 2025-05-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0011_rename_unit_price_receiptitem_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsale',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='cashsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_sales', to='pos_api.customer'),
        ),
        migrations.AlterField(
            model_name='cashsale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอน')], default='cash', max_length=20),
        ),
    ]
