# Generated by Django 5.2 on 2025-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0012_remove_cashsale_total_amount_alter_cashsale_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('Not approved', 'ไม่ได้รับการอนุมัติ'), ('converted', 'แปลงเป็นใบเสร็จรับเงิน'), ('reset', 'รีเซ็ต')], default='pending', max_length=50),
        ),
    ]
