# Generated by Django 5.2 on 2025-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0013_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('Not approved', 'ไม่ได้รับการอนุมัติ'), ('converted', 'แปลงเป็นใบเสร็จรับเงิน')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอน')], max_length=50),
        ),
    ]
