# Generated by Django 5.2 on 2025-05-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0014_alter_product_options_alter_receipt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
    ]
