# Generated by Django 5.2 on 2025-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0015_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
