# Generated by Django 5.2 on 2025-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0016_customer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('TH', 'ไทย'), ('MM', 'พม่า')], max_length=2),
        ),
    ]
