# Generated by Django 5.2 on 2025-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0017_alter_customer_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='viber_phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='viber_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
